name: communication_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  # flutter_sound: ^9.2.13
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  audio_session: ^0.1.10
  permission_handler: ^10.2.0
  firebase_core: ^2.1.1
  firebase_database: ^10.0.3
  firebase_storage: ^11.0.3
  # file_picker: ^5.2.2
  flutter_sound: ^9.2.13
  path_provider: ^2.0.11
  uri_to_file: ^0.2.0
  firebase_auth: ^4.1.1
  google_fonts: ^3.0.1
  cloud_firestore: ^4.0.4
  vxstate: ^2.3.0
  firebase_messaging: ^14.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
