// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmuQg9t7g-ukOEYyCBJOui2GJqSz3j1ow',
    appId: '1:375052660442:web:e7507ee9dbed6380923fe3',
    messagingSenderId: '375052660442',
    projectId: 'audiodash-64b7c',
    authDomain: 'audiodash-64b7c.firebaseapp.com',
    databaseURL: 'https://audiodash-64b7c-default-rtdb.firebaseio.com',
    storageBucket: 'audiodash-64b7c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg4Y0KlX2_FYXzUk_Arzc28vFNvyjfgZ4',
    appId: '1:375052660442:android:07d75d9bdc0e120c923fe3',
    messagingSenderId: '375052660442',
    projectId: 'audiodash-64b7c',
    databaseURL: 'https://audiodash-64b7c-default-rtdb.firebaseio.com',
    storageBucket: 'audiodash-64b7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA830pJFejtMNayNFN6htLduud9KXqkwA',
    appId: '1:375052660442:ios:edcdb9a04cddebe2923fe3',
    messagingSenderId: '375052660442',
    projectId: 'audiodash-64b7c',
    databaseURL: 'https://audiodash-64b7c-default-rtdb.firebaseio.com',
    storageBucket: 'audiodash-64b7c.appspot.com',
    iosClientId: '375052660442-10qiepnpgh53ajvig5rp525ipqqsov2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.audioDash',
  );
}
